version: '3.4'

services:
  web-service:
    build:
      context: .
      target: web
    image: bertytech/dev-web
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    command: yarn start

  tracer-service:
    image: jaegertracing/all-in-one:1.6
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  core-service:
    build:
      context: .
      target: core
    image: bertytech/dev-core
    ports:
      - "8701-8801:8700"
      - "1338-1438:1337"
    depends_on:
      - web-service
      - tracer-service
    volumes:
      - $GOPATH/src:/go/src
      - /tmp/go/pkg:/go/pkg
      - /tmp/go/bin:/go/bin

