version: '3.7'

services:
  daemon:
    container_name: betabot_daemon
    image: bertytech/berty:latest
    restart: always
    entrypoint: berty
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command:
      - daemon
      - "-store.dir=/store"
      - "-node.no-notif"
      - "-node.listeners=/ip4/0.0.0.0/tcp/9091"
      - "-p2p.ipfs-listeners=/ip4/0.0.0.0/tcp/6001,/ip4/0.0.0.0/udp/6001/quic"
      - "-p2p.ipfs-announce=/ip4/163.172.106.31/tcp/6001,/ip4/163.172.106.31/udp/6001/quic"
    volumes:
      - ./data/daemon/store:/store
    expose:
      - 6001

  betabot:
    container_name: betabot
    image: bertytech/berty:latest
    restart: always
    entrypoint: betabot
    links:
      - daemon
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command:
      - -display-name=BetaBot
      - -addr=daemon:9091
      - -staff-conversation-link=$BETABOT_STAFF_CONVERSATION_LINK
      - -store=/data/betabot.store
    depends_on:
      - daemon
    volumes:
      - ./data/betabot:/data
