berty:
  contacts:
    betabot:
      name: "BetaBot"
      link: "https://berty.tech/id#key=CiBYAkJkmvcCZOl2hWuSK34arbzSpcpQGLowIvi7ZsEdyRIgMmKs-zHKksC74gjOfSj5puOAQQGWNhsC8o9gEtQ8zrQ&name=BetaBot"
      description: "Official BetaBot"
      #icon:
    testbot:
      name: "TestBot"
      link: "https://berty.tech/id#key=CiCTp8uUnxfqlZaebiJEEt_zY-NUnHAWJl4jbGpB7rXsbxIg6_Grg-eLJ-GtqrdARnoTY35k7AI_g5AxqyFVe2elIaA&name=TestBot"
      description: "Official TestBot"
      #icon:
    betabot-dev:
      name: "BetaBot Dev"
      link: "https://berty.tech/id#key=CiBQHH6a84AHwdahXR6NQcOxTKjUHeqLdQfIAzxAYSoD1xIgT-tFTYrU-tD55bYgaXbBNTlqTHubq-_Qb8ksv2bSH9o&name=BetaBot%20Dev"
      description: "Dev BetaBot"
      #icon:
    #support:
    #staff:
    #berty-tv:
  conversations:
    dev-test:
      link: "https://berty.tech/group#invite=CiAbnwpJK0_Zg-pNE9bpcWKeI2J-RmCVuM7uNXQv7MEizBIg2EBkfV2eRm_SP5GX04H8zf9cpjsPTvMAcSeob3-GQsAaQPLmDQSArZfQ8QdANRX4uCrgQuivtF41pWnRYKEqDI_b1xb8mHExObf4RF9gcs4ktyMYVD6ZpCROyZfCg0f1GAAgAw&name=Dev+Test"
      name: "Dev Test"
      description: "Simple Conversation with Replication"
p2p:
  rdvp:
    # svc fr
    - maddr: "/ip4/51.159.21.214/tcp/4040/p2p/QmdT7AmhhnbuwvCpa5PH1ySK9HJVB82jr3fo1bxMxBPW6p"
    - maddr: "/ip4/51.159.21.214/udp/4040/quic/p2p/QmdT7AmhhnbuwvCpa5PH1ySK9HJVB82jr3fo1bxMxBPW6p"
    # svc ams
    - maddr: "/ip4/51.15.25.224/tcp/4040/p2p/12D3KooWHhDBv6DJJ4XDWjzEXq6sVNEs6VuxsV1WyBBEhPENHzcZ"
    - maddr: "/ip4/51.15.25.224/udp/4040/quic/p2p/12D3KooWHhDBv6DJJ4XDWjzEXq6sVNEs6VuxsV1WyBBEhPENHzcZ"
    # jorropo
    - maddr: "/ip4/51.75.127.200/tcp/4141/p2p/12D3KooWPwRwwKatdy5yzRVCYPHib3fntYgbFB4nqrJPHWAqXD7z"
    - maddr: "/ip4/51.75.127.200/udp/4141/quic/p2p/12D3KooWPwRwwKatdy5yzRVCYPHib3fntYgbFB4nqrJPHWAqXD7z"
