name: JS
on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - 'js/**'
      - '.github/workflows/js.yml'
  pull_request:
    paths:
      - 'js/**'
      - '.github/workflows/js.yml'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          #- 10.x
          #- 12.x
          - 14.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          js/node_modules
          js/packages/*/node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('js/**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    - name: "Fetch deps"
      run: |
        cd js
        make node_mod
      env:
        CI: true
    - name: "Run tests"
      run: |
        cd js
        make test
      env:
        CI: true
    - name: "Run lint"
      run: |
        cd js
        make lint
        ./node_modules/.bin/check-deps-sync .
      env:
        CI: true
