name: JS
on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - "js/**"
      - "config/**"
      - "tool/generate-i18n-testlang"
      - ".github/workflows/js.yml"
  pull_request:
    paths:
      - "js/**"
      - "config/**"
      - "tool/generate-i18n-testlang"
      - ".github/workflows/js.yml"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          #- 10.x
          #- 12.x
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: js/node_modules
          key: ${{ runner.OS }}-node-v4-${{ hashFiles('js/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-node-v4-
      - name: "Fetch deps"
        run: |
          cd js
          make node_modules
        env:
          CI: true
      - name: "Run tests"
        run: |
          cd js
          make test
        env:
          CI: true
      - name: "Run lint"
        run: |
          cd js
          make lint
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./js/coverage/coverage-final.json
          flags: js.unittests
          env_vars: OS,NODE_VERSION
          name: codecov-umbrella
          fail_ci_if_error: false
