name: Push

on: [push, pull_request]

jobs:
  cancel:
    name: 'Cancel Previous Workflows'
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}  # see https://github.com/actions/checkout/issues/299

      - name: Resolve IDS
        id: resolve-ids
        run: ./tool/build/shell/resolve-workflows-for-cancel.py

      - name: Cancel Workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: ${{ steps.resolve-ids.outputs.IDS }}
          access_token: ${{ github.token }}
